vu:
  quiz:
    total-questions: 10
    seconds-per-question: 90

server:
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb+srv://test:test@cluster0.ic9r7.mongodb.net/vuquiz
      database: vuquiz
