vu:
  quiz:
    total-questions: 10
    seconds-per-question: 90

server:
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb://localhost:27017/vuquizapp
      database: vuquizapp
